export { default as Layout } from './layout' 
export { default as Preloading } from './preloading' 
export { default as Header } from './header' 
export { default as Navbar } from './navbar' 
export { default as Hero } from './hero'
export { default as Travelstyle } from './travel-style'
export { default as Tour } from './tour'
export { default as Discount } from './discount'